# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              aemooooon's notes
description:        Kia ora, I'm Hua, a developer, a student and a father.

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo, image or text
logo:               # e.g. logo.png, upload logo image file to /assets/img/ folder
logo_text:          化十三爻      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Author settings, displayed on about page
author:
    name:           Wang Hua
    bio:            Kia ora, I'm Hua, a developer, a student and a father.
    email:          mailto:aemooooon@gmail.com
    website:        http://www.aemon.wang
    facebook:       https://www.facebook.com/hua.wang.71/
    github:         https://github.com/aemooooon/
    instagram:      https://www.instagram.com/aemooooon/
    linkedin:       https://www.linkedin.com/in/hua-wang-739244190/
    pinterest:      https://github.com/aemooooon/Project-Portfolio/blob/master/assets/img/p/WeChatQRcode.jpg?raw=true
# Social share buttons
twitter_username:   username
github_username:    username

# Site background color
template:           dark       # light or dark

# Default header image settings
header:
    image:          header.jpg  # upload your header image to /assets/posts/ folder
    align:          center      # top, center or bottom
    text:           light        # light or dark

# Default footer image settings
footer:
    image:          footer.jpg  # upload your header image to /assets/posts/ folder
    align:          center      #top, center or bottom
    text:           light       # light or dark
    copyright:      "&copy; aemooooon"

# Post settings
post:
    dropcap: true

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 7865

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key: AIzaSyCk8Ge_26DbfrhHt8oMNYZDG1LMN-96eBM

# Number of posts displayed on blog page
paginate:           10

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed
